var places = [
    [
        { 'image' : 1 }, 
        { 'image' : 4 }, 
        { 'image' : 9 }, 
        { 'image' : 17 }, 
        { 'image' : 6 }, 
        { 'image' : 20 }, 
        { 'image' : 21 }, 
        { 'image' : 24 }, 
        { 'image' : 26 }, 
        { 'image' : 29 }, 
        { 'image' : 23 }, 
        { 'image' : 23 }, 
        { 'image' : 11 }, 
        { 'image' : 22 }, 
        { 'image' : 1 }, 
        { 'image' : 30 }, 
        { 'image' : 7 }, 
        { 'image' : 22 }, 
        { 'image' : 22 }, 
        { 'image' : 21 }, 
        { 'image' : 32 }, 
        { 'image' : 29 }, 
        { 'image' : 4 }, 
        { 'image' : 27 }, 
        { 'image' : 0 }, 
        { 'image' : 0 }, 
        { 'image' : 24 }, 
        { 'image' : 24 }, 
        { 'image' : 1 }, 
        { 'image' : 7 }, 
        { 'image' : 1 }, 
        { 'image' : 32 }, 
        { 'image' : 4 }, 
        { 'image' : 10 }, 
        { 'image' : 11 }, 
        { 'image' : 8 }, 
        { 'image' : 29 }, 
    ],
    [ // 2nd row
        { 'image' : 2 }, 
        { 'image' : 20 }, 
        { 'image' : 4 }, 
        { 'image' : 9 }, 
        { 'image' : 8 }, 
        { 'image' : 1 }, 
        { 'image' : 22 }, 
        { 'image' : 11 }, 
        { 'image' : 27 }, 
        { 'image' : 8 }, 
        { 'image' : 9 }, 
        { 'image' : 1 }, 
        { 'image' : 27 }, 
        { 'image' : 9 }, 
        { 'image' : 2 }, 
        { 'image' : 27 }, 
        { 'image' : 8 }, 
        { 'image' : 11 }, 
        { 'image' : 7 }, 
        { 'image' : 7 }, 
        { 'image' : 18 }, 
        { 'image' : 28 }, 
        { 'image' : 27 }, 
        { 'image' : 33 }, 
        { 'image' : 18 }, 
        { 'image' : 8 }, 
        { 'image' : 11 }, 
        { 'image' : 7 }, 
        { 'image' : 11 }, 
        { 'image' : 1 }, 
        { 'image' : 29 }, 
        { 'image' : 1 }, 
        { 'image' : 9 }, 
        { 'image' : 7 }, 
        { 'image' : 8 }, 
        { 'image' : 33 }, 
        { 'image' : 28 }, 
    ],
    [ // 3rd row
        { 'image' : 2 }, 
        { 'image' : 6 }, 
        { 'image' : 8 }, 
        { 'image' : 18 }, 
        { 'image' : 7 }, 
        { 'image' : 11 }, 
        { 'image' : 7 }, 
        { 'image' : 1 }, 
        { 'image' : 28 }, 
        { 'image' : 26 }, 
        { 'image' : 11 }, 
        { 'image' : 21 }, 
        { 'image' : 8 }, 
        { 'image' : 2 }, 
        { 'image' : 32 }, 
        { 'image' : 9 }, 
        { 'image' : 8 }, 
        { 'image' : 1 }, 
        { 'image' : 18 }, 
        { 'image' : 1 }, 
        { 'image' : 1 }, 
        { 'image' : 8 }, 
        { 'image' : 9 }, 
        { 'image' : 6 }, 
        { 'image' : 23 }, 
        { 'image' : 7 }, 
        { 'image' : 8 }, 
        { 'image' : 2 }, 
        { 'image' : 18 }, 
        { 'image' : 24 }, 
        { 'image' : 29 }, 
        { 'image' : 11 }, 
        { 'image' : 2 }, 
        { 'image' : 18 }, 
        { 'image' : 1 }, 
        { 'image' : 23 }, 
        { 'image' : 8 }, 
    ],
    [ // 4th row
        { 'image' : 3 }, 
        { 'image' : 7 }, 
        { 'image' : 11 }, 
        { 'image' : 2 }, 
        { 'image' : 7 }, 
        { 'image' : 4 }, 
        { 'image' : 9 }, 
        { 'image' : 18 }, 
        { 'image' : 2 }, 
        { 'image' : 1 }, 
        { 'image' : 6 }, 
        { 'image' : 4 }, 
        { 'image' : 7 }, 
        { 'image' : 30 }, 
        { 'image' : 11 }, 
        { 'image' : 11 }, 
        { 'image' : 1 }, 
        { 'image' : 2 }, 
        { 'image' : 2 }, 
        { 'image' : 18 }, 
        { 'image' : 7 }, 
        { 'image' : 22 }, 
        { 'image' : 2 }, 
        { 'image' : 2 }, 
        { 'image' : -1 }, 
        { 'image' : 9 }, 
        { 'image' : 1 }, 
        { 'image' : -1 }, 
        { 'image' : 1 }, 
        { 'image' : 6 }, 
        { 'image' : 11 }, 
        { 'image' : 6 }, 
        { 'image' : -1 }, 
        { 'image' : 29 }, 
        { 'image' : 11 }, 
        { 'image' : -1 }, 
        { 'image' : 10 }, 
    ],
    [ // 5th row
        { 'image' : 2 }, 
        { 'image' : 18 }, 
        { 'image' : -2 }, 
        { 'image' : -2 }, 
        { 'image' : -3 }, 
        { 'image' : 29 }, 
        { 'image' : 23 }, 
        { 'image' : 2 }, 
        { 'image' : -1 }, 
        { 'image' : -3 }, 
        { 'image' : -3 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : 20 }, 
        { 'image' : 8 }, 
        { 'image' : 4 }, 
        { 'image' : -2 }, 
        { 'image' : -3 }, 
        { 'image' : -2 }, 
        { 'image' : 32 }, 
        { 'image' : 8 }, 
        { 'image' : -2 }, 
        { 'image' : 32 }, 
        { 'image' : 9 }, 
        { 'image' : -1 }, 
        { 'image' : -3 }, 
        { 'image' : -3 }, 
        { 'image' : -1 }, 
        { 'image' : 32 }, 
        { 'image' : 11 }, 
        { 'image' : 1 }, 
        { 'image' : 7 }, 
        { 'image' : -1 }, 
        { 'image' : 29 }, 
        { 'image' : -2 }, 
        { 'image' : -1 }, 
        { 'image' : 1 }, 
    ],
    [ // 6th row
        { 'image' : -1 }, 
        { 'image' : -2 }, 
        { 'image' : -2 }, 
        { 'image' : -2 }, 
        { 'image' : -3 }, 
        { 'image' : 8 }, 
        { 'image' : -3 }, 
        { 'image' : 3 }, 
        { 'image' : -1 }, 
        { 'image' : -3 }, 
        { 'image' : -3 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : 8 }, 
        { 'image' : 3 }, 
        { 'image' : 8 }, 
        { 'image' : 32 }, 
        { 'image' : -1 }, 
        { 'image' : -2 }, 
        { 'image' : -3 }, 
        { 'image' : 32 }, 
        { 'image' : -2 }, 
        { 'image' : -2 }, 
        { 'image' : -2 }, 
        { 'image' : -1 }, 
        { 'image' : -3 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -2 }, 
        { 'image' : 18 }, 
        { 'image' : 20 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -3 }, 
        { 'image' : -2 }, 
        { 'image' : -1 }, 
        { 'image' : 4 }, 
    ],
    [ // 7th row
        { 'image' : -1 }, 
        { 'image' : 8 }, 
        { 'image' : 13 }, 
        { 'image' : -2 }, 
        { 'image' : -3 }, 
        { 'image' : 2 }, 
        { 'image' : -3 }, 
        { 'image' : -2 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : 2 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : 18 }, 
        { 'image' : -3 }, 
        { 'image' : -3 }, 
        { 'image' : -2 }, 
        { 'image' : -2 }, 
        { 'image' : -2 }, 
        { 'image' : -1 }, 
        { 'image' : -3 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -3 }, 
        { 'image' : -2 }, 
        { 'image' : 29 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -3 }, 
        { 'image' : -2 }, 
        { 'image' : -1 }, 
        { 'image' : 23 }, 
    ],
    [  // 8th row
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : 31 }, 
        { 'image' : -2 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -3 }, 
        { 'image' : -2 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : 32 }, 
        { 'image' : -3 }, 
        { 'image' : -3 }, 
        { 'image' : -2 }, 
        { 'image' : -2 }, 
        { 'image' : -2 }, 
        { 'image' : -1 },  
        { 'image' : -3 },
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -3 }, 
        { 'image' : -3 }, 
        { 'image' : -3 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -3 }, 
        { 'image' : 29 }, 
        { 'image' : -1 }, 
        { 'image' : 1 }, 
    ],
    [ // 9th row
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : 12 }, 
        { 'image' : 8 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -2 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : 4 }, 
        { 'image' : -3 }, 
        { 'image' : -3 }, 
        { 'image' : -2 }, 
        { 'image' : 27 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -3 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -3 }, 
        { 'image' : -3 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -3 }, 
        { 'image' : 8 }, 
        { 'image' : -1 }, 
        { 'image' : 2 }, 
    ],
    [ // 10th row
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : 13 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : 25 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : 2 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : 2 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
    ],
    [ // 11th row
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : 14 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : 8 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : 32 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
    ],
    [ // 12th row
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : 15 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : 11 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : 27 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
    ],
    [ // 13th row
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : 16 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : 1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : 2 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
        { 'image' : -1 }, 
    ],
];

var known = [
    {
        'glyph' : 30,
        'char'  : 'c'
    },
    {
        'glyph' : 27,
        'char'  : 'o'
    },
    {
        'glyph' : 0,
        'char'  : 'v'
    },
    {
        'glyph' : 8,
        'char'  : 'e'
    },
    {
        'glyph' : 11,
        'char'  : 'r'
    },
    {
        'glyph' : 29,
        'char'  : 't'
    },
    {
        'glyph' : 29,
        'char'  : 't'
    },
    {
        'glyph' : 1,
        'char'  : 'a'
    },
    {
        'glyph' : 2,
        'char'  : 'n'
    },
    {
        'glyph' : 3,
        'char'  : 'w'
    },
    {
        'glyph' : 33,
        'char'  : 'x'
    },
    {
        'glyph' : 23,
        'char'  : 'm'
    },
    {
        'glyph' : 9,
        'char'  : 'u'
    },
    {
        'glyph' : 4,
        'char'  : 's'
    },
    {
        'glyph' : 20,
        'char'  : 'k'
    },
    {
        'glyph' : 6,
        'char'  : 'y'
    },
    {
        'glyph' : 7,
        'char'  : 'l'
    },
    {
        'glyph' : 17,
        'char'  : 'q'
    },
    {
        'glyph' : 18,
        'char'  : 'i'
    },
    {
        'glyph' : 21,
        'char'  : 'p'
    },
    {
        'glyph' : 22,
        'char'  : 'f'
    },
    {
        'glyph' : 24,
        'char'  : 'b'
    },
    {
        'glyph' : 26,
        'char'  : 'j'
    },
    {
        'glyph' : 28,
        'char'  : 'h'
    },
    {
        'glyph' : 32,
        'char'  : 'd'
    },
    {
        'glyph' : 10,
        'char'  : 'g'
    },
    {
        'glyph' : 10,
        'char'  : 'g'
    },
    {
        'glyph' : 31,
        'char'  : '3'
    },
];

$(document).ready(function(){
    var rows =  $('.row');
    
    var i = 0;
    
    rows.each(function(){
        var cols = $(this).children(".col");
        
        var j = 0;
        
        cols.each(function(){
            if (places[i][j].image >= 0) {
                var theChar = '';
                
                $.each(known, function(k, v){
                    if (known[k].glyph == places[i][j].image) {
                        theChar = known[k].char;
                    }
                });
                
                if (theChar === "") {
                    var filename = 'url(img/' + places[i][j].image.toString() + '.png)';
                    
                    $(this).css('background-image', filename);
                } else {
                    $(this).html(theChar);
                }
            } else {
                switch (places[i][j].image) {
                    case -1:    $(this).css('background-color', '#ddd');
                                break;
                    case -2:    $(this).css('background-color', '#ff9c93');
                                break;
                    case -3:    $(this).css('background-color', '#9191ff');
                                break;
                }
            }
            
            j++;
        });
        
        i++;
    });
    
    $.each(places, function(i, row) {
        $.each(row, function(j, col){
            // console.log('i: ' + i + ', j: ' + j + ', image: ' + col.image);
        });
    });
});